### ISSUE TITLE
[Add Issuer]: Li-Chun Chen/Chunghwa Telecom

### ISSUE THREAD

**Issue by lcchentw** [letsencrypt/ct-log-metadata#2]
### Mozilla Bugzilla Root Inclusion URL

https://bugzilla.mozilla.org/show_bug.cgi?id=1563417

### CA CP/CPS Website URL

https://eca.hinet.net/repository-h/en/index.htm

### CT Logs

- [X] Oak (production)
- [ ] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIIFajCCA1KgAwIBAgIQLd2szmKXlKFD6LDNdmpeYDANBgkqhkiG9w0BAQsFADBP
MQswCQYDVQQGEwJUVzEjMCEGA1UECgwaQ2h1bmdod2EgVGVsZWNvbSBDby4sIEx0
ZC4xGzAZBgNVBAMMEkhpUEtJIFJvb3QgQ0EgLSBHMTAeFw0xOTAyMjIwOTQ2MDRa
Fw0zNzEyMzExNTU5NTlaME8xCzAJBgNVBAYTAlRXMSMwIQYDVQQKDBpDaHVuZ2h3
YSBUZWxlY29tIENvLiwgTHRkLjEbMBkGA1UEAwwSSGlQS0kgUm9vdCBDQSAtIEcx
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA9B5/UnMyDHPkvRN0o9Qw
qNCuS9i233VHZvR85zkEHmpwINJaR3JnVfSl6J3VHiGh8Ge6zCFovkRTv4354twv
Vcg3Px+kwJyz5HdcoEb+d/oaoDjq7Zpy3iu9lFc6uux55199QmQ5eiY29yTw1S+6
lZgRZq2XNdZ1AYDgr/SEYYwNHl98h5ZeQa/rh+r4XfEuiAU+TCK72h8q3VJGZDnz
Qs7ZngyzsHeXZJzA9KMuH5UHsBffMNsAGJZMoYFL3QRtU6M9/Aes1MU3guvklQgZ
KILSQjqj2FPseYlgSGDIcpJQ3AOPgz+yQlda22rpEZfdhSi8MEyr48KxRURHH+CK
FgeW0iEPU8DtqX7UTuybCeyvQqww1r/REEXgphaypcXTT3OUM3ECoWqj1jOXTyFj
HluP2cFeRXF3D4FdXyGarYPM+l7WjSNfGz1BryB1ZlpK9p/7qxj3ccC2HTHsOyDr
y+K49a6SsvfhhEvyovKTmiKe0xRvNlS9H15ZFblzqMF8b3ti6RZsR1pl8w4Rm0bZ
/W3c1pzAtH2lsN0/Vm+h+fbkEkj9Bn8SV7apI09bA8PgcSojt/ewsTu8mL3WmKgM
a/aOEmem8rJY5AIJEzypuxC00jBF8ez3ABHfZfjcK0NVvxaXxA/VLGGEqnKG/uY6
fsI/fe78LxQ+5oXdUG+3Se0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
HQ4EFgQU8ncX+l6o/vY9cdVouslGDDjYr7AwDgYDVR0PAQH/BAQDAgGGMA0GCSqG
SIb3DQEBCwUAA4ICAQBQUfB13HAE4/+qddRxosuej6ip0691x1TPOhwEmSKsxBHi
7zNKpiMdDg1H2DfHb680f0+BazVP6XKlMeJ45/dOlBhbQH3PayFUhuaVevvGyuqc
SE5XCV0vrPSltJczWNWseanMX/mF+lLFjfiRFOs6DRfQUsJ748JzjkZ4Bjgs6Fza
ZsT0pPBWGTMpWmWSBUdGSquEwx4noR8RkpkndZMPvDY7l1ePJlsMu5wP1G4wB9Tc
XzZoZjmDlicmisjEOf6aIW/Vcobpf2Lll07QJNBAsNB1CI69aO4I1258EHBGG3zg
iLKecoaZAeO/n0kZtCW+VmWuF2PlHt/o/0elv+EmBYTksMCv5wiZqAxeJoBF1Pho
L5aPruJKHJwWDBNvOIf2u8g0X5IDUXlwpt/L9ZlNec1OvFefQ05rLisY+GpzjLrF
Ne85akEez3GoorKGB1s6yeHvP2UEgEcyRHCVTjFnanRbEEV16rCf0OY1/k6fi8wr
kkVbbiVghUbN0aqwdmaTd5a+g744tiROJgvM7XpWGuDpWsZkrUx6AEhEL7lAuxM+
vhV4nYWBSipX3tUZQ9rbyltHhoMLP7YNdnhzeSJesYAfz77RP1YQmCuVh6EfnWQU
YDksswBVLuT1sw5XxJFBAJw/6KXf6vb/yPCtbVKoF6ubYfwSUTXkJf2vqmqGOQ==
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by aarongable** [comment]
I've confirmed that the certificate here is identical to the certificate included in the Mozilla Root Store as a result of the bug linked above. We should include it in our list of accepted roots, and I'm actually slightly surprised that it apparently isn't included already. Assigning to @pgporada for inclusion in //issuers/common/.

**Comment by pgporada** [comment]
@lcchentw Sorry for the very long delay. I was working through some tooling improvements and have finally come back to this repository. I'll get your roots deployed to Sapling and Oak by tomorrow and will post another update here as soon as that's done.

**Comment by pgporada** [comment]
@lcchentw Your root has been included in all existing oak shards.

**Comment by lcchentw** [comment]
Thank you very much for your help.

**Comment by lcchentw** [comment]
> Reference
> @lcchentw Your root has been included in all existing oak shards.

It seems like our root CA certificate (HiPKI Root CA -G1) still doesn't be included in the oak shards, such as [https://oak.ct.letsencrypt.org/2023/ct/v1/get-roots], Please check the oak shards.

Thank you for all your assistance.

**Comment by pgporada** [comment]
🤦🏼 That's my fault during the sync from this repository to the operational repo. Here you go.
```
for shard in 2022 2023 2024h1 2024h2; do for cert in $(curl -s "https://oak.ct.letsencrypt.org/${shard}/ct/v1/get-roots" | jq -r '.certificates | .[]' | sort | uniq); do     echo -e "-----BEGIN CERTIFICATE-----\n${cert}\n-----END CERTIFICATE-----" | openssl x509 -noout -serial | grep -i 2DDDACCe629; done; done
serial=2DDDACCE629794A143E8B0CD766A5E60
serial=2DDDACCE629794A143E8B0CD766A5E60
serial=2DDDACCE629794A143E8B0CD766A5E60
serial=2DDDACCE629794A143E8B0CD766A5E60
```

**Comment by lcchentw** [comment]
> Member @pgporada 


 We see our root CA certificate has been successfully included, thanks for your assistance.
