### ISSUE TITLE
[Bug]: add-root-to-log.sh doesn't support roots with duplicate O and CN fields

### ISSUE THREAD

**Issue by aarongable** [letsencrypt/ct-log-metadata#22]
### Bug Report

These roots have identical O and CN fields, differing only in their OU:
https://ccadb.force.com/s/account/001o000000HshF3AAJ/globalsign
https://ccadb.force.com/s/account/001o000000OrML1AAN/globalsign
https://ccadb.force.com/s/account/001o000000rGWc7AAG/globalsign

When we run add-root-to-log.sh on these roots, it just keeps replacing the contents of the file named `'GlobalSign - GlobalSign.crt'`.

One solution would be to incorporate the OU field into the filename. Another solution would be to detect duplicate filenames, and append an increasing integer to the end. Another solution would be to change the root ingestion method entirely, to something like "batch process a CSV downloaded from CCADB" (which could then be turned into a process that simply runs once a quarter or so).

**Comment by jcjones** [comment]
Despite this change, we seem to have left behind 14 roots in the update for the Sapling shards, so some roots with duplicates have as of tonight been excluded from Sapling.

Also, we need to handle SKIDs in the `pull-roots-from-all-shards` script, and audit why we're missing roots in the currently-checked-in accepted roots files.

**Comment by jcjones** [comment]
Fixed by #28.
