### ISSUE TITLE
[Add Issuer]: Actalis Authentication Root CA Test

### ISSUE THREAD

**Issue by defacto64** [letsencrypt/ct-log-metadata#29]
### Mozilla Bugzilla Root Inclusion URL

We are already trusted by all major Root CA programs, and alerady using a number of CT Logs. This request is just for being able to submit test pre-certificates to a test CT Log, such as Sapling, from a new test CA environment that we are setting up, but no now roots are planned.

### CA CP/CPS Website URL

https://www.actalis.com/ssl-certificates.aspx

### CT Logs

- [ ] Oak (production)
- [X] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIIFyzCCA7OgAwIBAgIQBB/O3nHn5Uld2sThl8vfjjANBgkqhkiG9w0BAQsFADBv
MSwwKgYDVQQDDCNBY3RhbGlzIEF1dGhlbnRpY2F0aW9uIFJvb3QgQ0EgVGVzdDEX
MBUGA1UECgwOQWN0YWxpcyBTLnAuQS4xGTAXBgNVBAcMEFBvbnRlIFNhbiBQaWV0
cm8xCzAJBgNVBAYTAklUMB4XDTIyMTIzMDE0MjkzOFoXDTQyMTIyNTE0MjkzN1ow
bzEsMCoGA1UEAwwjQWN0YWxpcyBBdXRoZW50aWNhdGlvbiBSb290IENBIFRlc3Qx
FzAVBgNVBAoMDkFjdGFsaXMgUy5wLkEuMRkwFwYDVQQHDBBQb250ZSBTYW4gUGll
dHJvMQswCQYDVQQGEwJJVDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
ANvPG2dZJbAXCBYb4mA1/kfnzBFJ855V3CgKn9ruXQevQtAJiOC+vNjEVPO1wioP
Cl92PK+uqehgL1WLh9+js3895LZic5vHPNxTkw1mgZ08yv5Ues90R585LAt0WchG
/EG25fssdx1yYRWyniKpelGldsrCsQP1iseWBIXoEZqHDTiY/c6I8GEbZYR8g8w1
fRiGNRhYlLq8duxZt+FmmVE6nDza6isApiGUg+UiMxDBFqAmtTOSvjCvJFyfn6OM
lLO6CIWAwmLDARWROwIe9YXFtpxuoF2nF4rJ+9JCmpdbwylhbL63sagNgwy3uXuv
CSwMyOOQ908CJcSZm2BOltLu64GjNKUW6nDTNgCUotx8IqbAhUG3C48oPFq145R0
yzZQ9NUaILkkkbs+3bocXFzRezhuhBNArqXDKRFLeiJUP693ooBmW3r5ClQgmhDl
TAkH7R6cdON4rwoTN5t1EqsXQs1gi+Bx45nLI00CcoEqpBFC/Und2JWHqte6Rubh
ZvyQ0oOiNtkJ17iDb6Ha1dac0JKxnsXLdWTgBzNFqgcEHKHu9kYjtzpd3toZ5qIJ
8XrAxVSZgMAMwdOC+hqO3bmsdZB9gAV97y42pquUYoqfRslHY1pTQ/CXoyPvG1NC
jLmg0kEoszKUm6FQzzdUwK2CISZ2q/dk7ZMOkAyhwnXrAgMBAAGjYzBhMA8GA1Ud
EwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUMqohKkFKsQjpoXDTwiyz1FtCobowHQYD
VR0OBBYEFDKqISpBSrEI6aFw08Iss9RbQqG6MA4GA1UdDwEB/wQEAwIBhjANBgkq
hkiG9w0BAQsFAAOCAgEA2VL/P07k3BMxbalX2PHSr6gcHQIfpUyAZmavQX4mWJS3
vBfRNTIJuVGkF4ltDFz8lg9iqGSrtRvDNmvJTJ+F2gKt95lWtq5RNJrT+d6faggB
UYuA0q5SeXpi7ndqQBtMPQyvy2VYHv2fbJekwqtOhBdjoWhopw81asv6x43v+LPt
CbpKIqXHFI+Y5s/Cad6150KVA/LPBK/wk+9crgq/heKlCYpVtJxtZkF4Ot/mm2bX
FPEnEgn77UpxVcfTsWSSNOYpUP7+bRQ82s5iqft3vWjqPlVOwvtFEtPu6qiyJQ2b
vSheNjf9CKkW35cIcFhc1Bz+QkSws1jyJveyho3mol+BLXam0Qer2rWAB1fvvGjW
GnNBjh0Svij+DWeaOOf94Un9pnp+F5DnpX1pee+1rmGYJXK66Cm5HKv1d2LE74lq
kUl72xR9N6zpAUy2n34QLRWySpNNNGUdu9INP7yNPIFhwXEE1hS6zs9SeljIUQhu
l2t7LS3f7rqJFYiRvsMhr23hcCAMfmVnCs/zWSSU/U0C8cQwNGvg5SeQ7GwXOpBh
/fEucYHL93YRjpApqdaCjo8fdMD7ilQ8NNBD1hr7M6u3R7S8eSDPSawldgTQNo9F
xGzrnFx8yJUprFkc62zzo7LjxpF4GIICavKduRrNr4DCBtSXuQIxynkoai9wTaE=
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by mcpherrinm** [comment]
Your root has been added to the configuration for the Sapling CT log.

I will deploy the changes soon, likely within a few hours.

**Comment by mcpherrinm** [comment]
This change is now live. 

Validated with:

```
curl https://sapling.ct.letsencrypt.org/2023h1/ct/v1/get-roots | jq -r .certificates[] | base64 -d | certigo dump -f DER -v | grep "32:AA:21:2A:41:4A:B1:08:E9:A1:70:D3:C2:2C:B3:D4:5B:42:A1:BA" -B16 -A6
```

**Comment by defacto64** [comment]
Thank you.

**Comment by defacto64** [comment]
May I ask you a question, although the issue is closed. Is it correct to say that you do not run a test CT log suitable for certificates with a validity longer than 6 monhs? For instance, if we wanted to log a certificate of 1y validity, for testing purporses, it seems we could not rely on Sapling 2023h1....

**Comment by mcpherrinm** [comment]
We're a bit behind on setting up the next shards for Sapling, but we should have that done soon, in the next few weeks.  Since we internally only issue 90 day certificates it hasn't been a pressing issue for us yet.  But we should have shards available for 1 year certificates normally.
