### ISSUE TITLE
[Add Issuer]: Kamu SM Test Root

### ISSUE THREAD

**Issue by mte517** [letsencrypt/ct-log-metadata#32]
### CT Logs

- [ ] Oak (production)
- [X] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIIESjCCAzKgAwIBAgIGWyX+DAHCMA0GCSqGSIb3DQEBCwUAMIHDMQswCQYDVQQG
EwJUUjEXMBUGA1UEBwwOR2ViemUgLUtvY2FlbGkxRzBFBgNVBAoMPlTDvHJraXll
IEJpbGltc2VsIHZlIFRla25vbG9qaWsgQXJhxZ90xLFybWEgS3VydW11IC0gVMOc
QsSwVEFLMRAwDgYDVQQLDAdCxLBMR0VNMUAwPgYDVQQDDDdLYW11IFNNIEvDtmsg
U2VydGlmaWthIEhpem1ldCBTYcSfbGF5xLFjxLFzxLEgLSBURVNUIFMyMB4XDTIx
MDgyNTExMTg0OFoXDTMxMDgyMzExMTg0OFowgcMxCzAJBgNVBAYTAlRSMRcwFQYD
VQQHDA5HZWJ6ZSAtS29jYWVsaTFHMEUGA1UECgw+VMO8cmtpeWUgQmlsaW1zZWwg
dmUgVGVrbm9sb2ppayBBcmHFn3TEsXJtYSBLdXJ1bXUgLSBUw5xCxLBUQUsxEDAO
BgNVBAsMB0LEsExHRU0xQDA+BgNVBAMMN0thbXUgU00gS8O2ayBTZXJ0aWZpa2Eg
SGl6bWV0IFNhxJ9sYXnEsWPEsXPEsSAtIFRFU1QgUzIwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCV7LNZSNVG/VFdEFnTbkh3pWppLgC+LtIdnFiaYERP
gDCDFZwm9G8DCcjxcyvaPrUzaFjqxqtDbwmeVzaCMN4qQaii/OS8vGhZpsOZroKr
q6lfBhkUBt46BHgUwjUIoQUQxaHVxSsZhdrVrTzDf4R8zQ/YYTIbjZ4dBAkf7Nma
E8ZHJpycpuCGDJaZzLTVHtST6rvYmYvRfpDsfZzgb9bwwBmzxmnVPDHOZ/QGFswv
K8EQeO22vdUsNvyNkGxgOj4v9vUKnrfEOHWU4h6TFu+mVaxPupwl8GIAcd5C1pse
jVr6byO34YSZgf5ijgV8Djf12nNafLs6Hy7oT363+tB7AgMBAAGjQjBAMB0GA1Ud
DgQWBBTkNvaP2f8sqbZ3fJkBE3jNd8Bi5TAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0T
AQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAfjuP3WWsSBuTqq09F5PjuGVp
nZiyGWVN8C0aq1iEjB+s2ZyHn0NZ5YXUY+2R+COO1lrXExNOO6HfZDhi0YcLkFso
VxDjHCy5YiNlPjMVgTHQXW3/qjFQHxw6X9f6t2VpRiX+aie6jPEx2yQ7KHl5BsZr
x9u5XiEryVGov6RT1HF5OZpvup0KiVGatKDM7GymMX2orWGi/AIJl+f8D4vU7nSX
c6O4tnJLsv0PUhlNEO5OqJ8jK+GY7eIWwC/UzrMhKr/cwF+tvtEXgTa1ZWTLp3NB
1TVOKYk6g4gBRhij3gumjwgQzANEM0ObbhvOI4zGePk43fMKq/xJyL+ZXNGuOQ==
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by mte517** [comment]
Kamu SM [prod root certificate](http://depo.kamusm.gov.tr/ssl/SSLKOKSM.S1.cer) is already trusted by all major root CA programs and CT log servers including your Oak CT log. This request is just for being able to submit test certificates.

**Comment by mcpherrinm** [comment]
This seems fine.  We should be able to add this to Sapling (test log) within the next week.

**Comment by mte517** [comment]
Thank you for your help in this matter.

**Comment by andygabby** [comment]
We have added Kamu SM Test Root as an accepted root to our Sapling log shards.
