### ISSUE TITLE
[Add Issuer]: AS207960 test root

### ISSUE THREAD

**Issue by TheEnbyperor** [letsencrypt/ct-log-metadata#36]
### CA CP/CPS Website URL

https://acmeforonions.org

### CT Logs

- [ ] Oak (production)
- [X] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIICsTCCAjigAwIBAgIUET8oCxgBAMLulJa0Efa25KjwTgMwCgYIKoZIzj0EAwQw
gYYxCzAJBgNVBAYTAkdCMQ4wDAYDVQQIDAVDeW1ydTEcMBoGA1UECgwTQVMyMDc5
NjAgQ3lmeW5nZWRpZzEuMCwGA1UECwwlQVMyMDc5NjAgRGVwYXJ0bWVudCBvZiBS
YW5kb20gTnVtYmVyczEZMBcGA1UEAwwQQVMyMDc5NjAgVGVzdCBDQTAgFw0yMTA2
MDgxNjM5NTlaGA8yMDcxMDUyNzE2Mzk1OVowgYYxCzAJBgNVBAYTAkdCMQ4wDAYD
VQQIDAVDeW1ydTEcMBoGA1UECgwTQVMyMDc5NjAgQ3lmeW5nZWRpZzEuMCwGA1UE
CwwlQVMyMDc5NjAgRGVwYXJ0bWVudCBvZiBSYW5kb20gTnVtYmVyczEZMBcGA1UE
AwwQQVMyMDc5NjAgVGVzdCBDQTB2MBAGByqGSM49AgEGBSuBBAAiA2IABOj4cU1O
IOfZbJfUBfudoy89Pqy9iK1pbvEsnSxgLzTco3pnb79e0/8cCDkefUcMJCmd4BeM
HflMxPDUwJDhTl9jmfj5Y0WdXIE8A/e5fwwfS7ejIykNXjvLpVn6imYGWaNjMGEw
HQYDVR0OBBYEFP2gqXjQroXnMegLUU3Y4CQ0cxV+MB8GA1UdIwQYMBaAFP2gqXjQ
roXnMegLUU3Y4CQ0cxV+MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGG
MAoGCCqGSM49BAMEA2cAMGQCMG+WBaLRGJQSpoWbflYmxYROLP7lWfb6CM3O9BlU
oxSvW9WP+af87XMxmeIJZswZBwIwMicNgKCb1DBUwSp22mq5PrRe3EOq8acJXmo6
NZ/8KXW2J/oNbhmbssJfpO8+qXuY
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by mcpherrinm** [comment]
Hello!

Our intention with our Sapling test log is primarily for CAs who intend to integrate with our production logs (Oak).

We typically recommend test CAs can test against https://github.com/letsencrypt/boulder/tree/main/test/ct-test-srv which implements the submission APIs typically used by CAs.

Do you require these certs to be in a public log?

What volume of test certificates do you expect to be submitted?

Thank you!

**Comment by TheEnbyperor** [comment]
The CA is supposed to act like any other publicly trusted CA as closely as possible, so inclusion in a public log would be desired.

In terms of volume I expect on the order of dozens a month, or less.

**Comment by TheEnbyperor** [comment]
> Do you intend to create a public CA that is trusted by the Mozilla or other root programs?

Yes that is in our plans, however not with this specific public key.
