### ISSUE TITLE
Removal of e-Tugra root certificate

### ISSUE THREAD

**Issue by nagaripratap** [letsencrypt/ct-log-metadata#37]
Description
Certifi 2023.07.22 removes root certificates from "e-Tugra" from the root store. These are in the process of being removed from Mozilla's trust store.

e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).

Informations

Manifest Path : [tooling/accepted_roots/ccadb.csv](https://github.com/letsencrypt/ct-log-metadata/blob/d060d373ff3a3b5837825873426c0c55424f2e46/tooling/accepted_roots/ccadb.csv#L1095)

**Comment by mcpherrinm** [comment]
It's desirable to allow distrusted roots in CT logs, so that any additional certificates which are issued are still logged.  

They will get removed at some point in the future
