### ISSUE TITLE
Include twelve missing roots

### ISSUE THREAD

**Issue by aarongable** [letsencrypt/ct-log-metadata#42]
### Bug Report

Rob Stradling's [new report](https://crt.sh/accepted-roots-missing) indicates that Oak does not accept submissions chaining up to 12 roots that are included in various root programs. We need to include these roots.
* [Network Solutions CA](https://crt.sh/?id=7677)
* [GlobalSign](https://crt.sh/?id=8644166)
* [GTS Root R3](https://crt.sh/?id=139646519)
* [GTS Root R1](https://crt.sh/?id=139646520)
* [GTS Root R2](https://crt.sh/?id=139646522)
* [GTS Root R4](https://crt.sh/?id=139646525)
* [GlobalSign Secure Mail Root R45](https://crt.sh/?id=2833787760)
* [GlobalSign Secure Mail Root E45](https://crt.sh/?id=2858272562)
* [HARICA Client RSA Root CA 2021](https://crt.sh/?id=4147049674)
* [HARICA Client ECC Root CA 2021](https://crt.sh/?id=4147052292)
* [Atos TrustedRoot Root CA ECC TLS 2021](https://crt.sh/?id=7077688374) (#40)
* [Atos TurstedRoot Root CA RSA TLS 2021](https://crt.sh/?id=7077692599) (#39)

These are missing from all of our current log shards (2023 - 2025h2).

**Comment by mcpherrinm** [comment]
We should be including the Apple and Chrome trust stores from CCADB, not just Mozilla.

**Comment by lenaunderwood22** [comment]
Accepted roots have been updated with all of the above for shards Oak-2023, Oak-2024h1, Oak-2024h2, Sapling-2023h1, Sapling-2023h2.
