### ISSUE TITLE
[Day One]: Add Test Root CA for CT Log Testing 

### ISSUE THREAD

**Issue by AAG9** [letsencrypt/ct-log-metadata#45]
### CT Logs

- [ ] Oak (production)
- [X] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIIDPTCCAiWgAwIBAgIRAKy9ko/ZGrSR7PmGTQZxoD4wDQYJKoZIhvcNAQELBQAw
ODELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB0RheSBPbmUxFzAVBgNVBAMMDlRlc3Qg
Um9vdCBDQSAxMB4XDTI0MDUyMjAxMDUyN1oXDTM0MDUyMjAyMDUxOVowODELMAkG
A1UEBhMCVVMxEDAOBgNVBAoMB0RheSBPbmUxFzAVBgNVBAMMDlRlc3QgUm9vdCBD
QSAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKHnHKnCxA+AHGkg
biUf0xRoGJmKOLdSz9o4weyzkkgW7OUlGH0mmuyQ55K0RyMv/qACetehgZpZeqtR
U+tzEJhqOZXaqBYzvqP3R19FL0Y63HBIjMV/wkbxqyoQ2Q1MXY/UVsj4/c+PHBr/
NxCAklKzLI8pTZjvR/V0JQ3seHwl5s+uPMy6FmpNgst1mWhcUbEErQ7RoDWsAy2Z
A/J5jWT3BASOI3dOWQQmjgSJ44mCKkTfRMTzXG7sObc5pyH5XN31OqfvkFUbCW2s
4UIBUgbEuPx7kuVaY+c2xTDn64prkjVcAcpf7nYlkAkuFjxE4K7yxG9PLdJpHLtl
zLsMDQIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRlLBRUtJJq
j4pmChQjAyIwdZBQpTAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQELBQADggEB
AF73xpu9cQkKFZsyPnfGyddJHlEoRv54InxbJdFoSYfmG5NAPW1MhyyvCLt/gvI8
Jr5Mm5XfMPbM3uNOmVo1bYXeuqH0JTEzJsmcxU5Jxbo69HmZHFCY+OKLFbw42EOc
w/w2EGSrg+xsPjSmTc8bpATmjoOLmX6EuUVFSNKeUcPkvi+VBw0Xc/wQqrMlLhUw
qSs+IZQbuz7it9MAyhSfIScdl176vv/bxW8QSnSy+a5RvJupVVQ/u8gJtlNhdLOS
QncS4K6kFRfiximY59jbDrfJsT2/8W9zx0o2CaVsud36UaN6DHXXmxVaBVRrbgze
R2iTCu8WszxUqUqw+40vQD0=
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by aarongable** [comment]
Hi Ameya, you haven't provided a root inclusion request URL or a CP/CPS URL -- can you clarify whether Day One is a CA that will be seeking inclusion in various trust stores in the future?

**Comment by AAG9** [comment]
Hi Aaron, thanks for getting back to me. Yes, Day One is not a public CA and will never be. My aim is to test the CT logging functionality using Lets Encrypt Sapling environment hence I have included a privately created root which does not have a root inclusion or CPS URL and will never have.

**Comment by mcpherrinm** [comment]
The sapling log is intended for integration testing in preparation of using Oak for submitting publicly trusted roots.

If you want to test CT submission for a private CA, you should consider running your own log for your test environment.
