### ISSUE TITLE
[Add Issuer]: 

### ISSUE THREAD

**Issue by DavidMunoa** [letsencrypt/ct-log-metadata#54]
### Mozilla Bugzilla Root Inclusion URL

https://ccadb.my.site.com/001o000000HsfpCAAR

### CA CP/CPS Website URL

https://www.izenpe.eus/contenidos/informacion/doc_juridica/en_def/adjuntos/IZNP_CP_Website_authentication_certificates_v2.3.pdf

### CT Logs

- [ ] Oak (production)
- [X] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIICJzCCAa6gAwIBAgIQMRDhDlWBehwWmlg+94z7IzAKBggqhkjOPQQDAzBFMQsw
CQYDVQQGEwJFUzEUMBIGA1UEChMLSVpFTlBFIFMuQS4xIDAeBgNVBAMTF1JPT1Qg
Q0EgU1NMIElaRU5QRSAyMDI0MB4XDTI0MDkwMjEwNDgyOFoXDTQ5MDkwMjExMTgy
OFowRTELMAkGA1UEBhMCRVMxFDASBgNVBAoTC0laRU5QRSBTLkEuMSAwHgYDVQQD
ExdST09UIENBIFNTTCBJWkVOUEUgMjAyNDB2MBAGByqGSM49AgEGBSuBBAAiA2IA
BK9iifVl/0JM3JXNVomzky10Fhgv5D5J70dbgx6q3UEDLgd6tw9GJ4x3trVMLSnC
y05Q8ZP1ZRBBTi71ghEf/Id3FIc31/nRztcLJr+7MvbY7TWaLqegMnaAi/37Vd4w
RKNjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgw
FoAULBql8ydxZHv4mPCbwjjs4Lg2J5cwHQYDVR0OBBYEFCwapfMncWR7+Jjwm8I4
7OC4NieXMAoGCCqGSM49BAMDA2cAMGQCMBgiIKRpHFHE2KWdcJxmCn3dZ9cn6MwB
YFWFm+zpPBkzfLv5veRhhrPPYYW1S1VNpAIwRtbTdCZELtr3doi1CPyrvoC5zj1M
S6lhM+8/x0srV22ryY3G+0+ii+SVHL0z3SJc
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by aarongable** [comment]
The Sapling log is primarily intended for use by untrusted testing infrastructure, not preflight testing for soon-to-be-trusted hierarchies.

It looks like there is not yet a Root Inclusion Request for this new Root CA Certificate. When there is, re-apply for inclusion in both the Oak and Sapling logs.

**Comment by DavidMunoa** [comment]
Hi Aaron,
this root is for our testing infrastructure. The problem we have is that it's been generated using the same subject than the production one (which will be submitted for Root Incluision soon) and I understand that this can lead to missunderstandings.
We just wanted to test our new infrastructure with the new keys generated on it and perform some tests related to the CT.
Thanks for all.
Regards,
