### ISSUE TITLE
[Add Issuer]: Please Add "TrusAuth High Assurance EV Root CA" Certificate

### ISSUE THREAD

**Issue by LeviMarvin** [letsencrypt/ct-log-metadata#8]
### CA CP/CPS Website URL

https://www.trusauth.eu.org/cps/

### CT Logs

- [ ] Oak (production)
- [X] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIIGKzCCBBOgAwIBAgIIUFCMZtBDEhowDQYJKoZIhvcNAQELBQAwbTEVMBMGA1UE
ChMMVHJ1c0F1dGggSW5jMScwJQYDVQQLEx5UcnVzQXV0aCBDZXJ0aWZpY2F0ZSBB
dXRob3JpdHkxKzApBgNVBAMTIlRydXNBdXRoIEhpZ2ggQXNzdXJhbmNlIEVWIFJv
b3QgQ0EwIBcNMjIwMTAxMDAwMDAwWhgPMjA1MTEyMzEyMzU5NTlaMG0xFTATBgNV
BAoTDFRydXNBdXRoIEluYzEnMCUGA1UECxMeVHJ1c0F1dGggQ2VydGlmaWNhdGUg
QXV0aG9yaXR5MSswKQYDVQQDEyJUcnVzQXV0aCBIaWdoIEFzc3VyYW5jZSBFViBS
b290IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0y47YZFdlkxm
Cjq0zBhDBFVexUGeFIhs+3Q6mdmb/zuUj5uU6nxYUePlTeW4I2dnHbymHVC8bEyK
ihMHcpeSMGYq8XeKT5g0Xbty3dLPNqqBnTVET9RFKhJfagPBFFcW+8lkvONo6HTL
4tXTrqdaZ6rhHbAZ5RJY3IlhQqQKMKoohokA0Uu9j7pT2OIkK2IhiuHFdLbaXes7
+tY4Hrs/SLdzhoGxaiS5/JaQufHSIL3D3RLddGUS2dfu+GcVg3rEI52llSgvzxa0
7fa5yiOk03CzgWh1MmSyC6KmxoDkWBl/K851Zb55bi3xbYDbcdNYIFDKQAzzTNfu
rebSN/Lw8zGQ7cdYjfSoul4wundLmJYug1ZvU+6RKDkxXE69NZ0r+xMQ1mpkbx1S
H+snpZqm0cU4XWGg1230jGnJhU647H/04qt+cy7XjKheaX+TVFVCMRhl8IqxEtKX
ZcGG0gMljhxCCla8l5qw9ndE8WHIn3e9y2wVQ4Pqi7MtQelWY3JquubNQm0OwPwU
9ZiqPm9yTFStNSskcb/RKPP2hcaIARsiQVhOssQBCZTUrrVhd1TmyQ7O7HtnaJtN
7Hg/ywxsmwN26pdqsCViQ8sgoK//KhRt+khm97+gsPy8oBsyd1VpOwhgiXXqhpMS
cLnFRycyJKfLZktsmfpDCqYaGRX6smkCAwEAAaOBzDCByTCBhgYDVR0jBH8wfaFx
pG8wbTEVMBMGA1UEChMMVHJ1c0F1dGggSW5jMScwJQYDVQQLEx5UcnVzQXV0aCBD
ZXJ0aWZpY2F0ZSBBdXRob3JpdHkxKzApBgNVBAMTIlRydXNBdXRoIEhpZ2ggQXNz
dXJhbmNlIEVWIFJvb3QgQ0GCCFBQjGbQQxIaMA8GA1UdEwEB/wQFMAMBAf8wHQYD
VR0OBBYEFHj4BVpL3v+u+UViXzuunPp2l64GMA4GA1UdDwEB/wQEAwIBhjANBgkq
hkiG9w0BAQsFAAOCAgEAmrVwmJO3eQQwPLPLGC0FavtwsoydCSgW9maJQvZvmOK3
R1nAMfesHUX0MHo9xHyPWdfoEIH2Ic6LTnaHZOiJEfpSc/Mh0oXIwvxzYyH83ioM
4a40fSlji+MyJgf+UtHZ+TEoS11Xbs9rKuXhNHs4GJI9zmE+ddvXjlpRlQCoGkL1
thIln5NgL/zgTR06MNSmJuscwUorQWAI568tRAbbseYjjl/0ozSZ+Abwt4K9Vg7E
fMf1XswFaDSnofd9smll9b4gI2M1Ycrp2HaMQXXMk4cQ8NwXQF5tunUhgPFjkX0P
TRxQ5aLnmKm/lKemXcl95NUYpBtF21QLDOfLfqNHBPpTt6FOl5M0ueCMfYcBpZF7
fOyxJlNtokbpNlAQu+wSHxAH1xPsdOm+rOMUEcfeMSHerGxeTEQT5ZQxgFOOICnG
8M2gz96NNGd+q0z56eay0nktE6rKG74wjUHNbuHswKwHUg7+htFrzB7q6RO57CQj
omUdQoIDG2WYOO0XGDokwWDjCoSx/4RVBett8qQSRqXCK4H7YsxNlyrNSpBVCyQ6
vJXXZzg3A++vPGg7nSB/I/98wAaRauZG9qhdB7EURQ8X42BQooIhTn7VL1BM8C2+
5SdWiWAS/p2qTtUdUC4nX1gWYbwN5SU7s1Zl66Nz0Sw8dlxP2+GTiglhp45Geb4=
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by pgporada** [comment]
Hi @LeviMarvin,

Thank you for submitting all of these root inclusion requests. At this time I will not be accepting these roots into Sapling. Instead, my suggestion is to use the [ct-test-srv](https://github.com/letsencrypt/ct-log-metadata#ct-test-srv) software to test your CA implementation in preparation for your roots being accepted into the Mozilla/Chrome/Apple CA root programs. Once progress has been made getting your root certificates incorporated into those WebPKI root programs, I'd be happy to add your roots to Sapling.

> Sapling is a preproduction log, intended for certificates which are not publicly trusted, but *which are issued by Certificate Authorities who either issue or are expected to issue publicly trusted certificates*.
