### ISSUE TITLE
[Add Issuer]: Please Add "TrusAuth High Assurance EV Root CA - G4" Certificate

### ISSUE THREAD

**Issue by LeviMarvin** [letsencrypt/ct-log-metadata#9]
### CA CP/CPS Website URL

https://www.trusauth.eu.org/cps/

### CT Logs

- [ ] Oak (production)
- [X] Sapling (testing)

### Issuer Certificate

-----BEGIN CERTIFICATE-----
MIIC7DCCAnOgAwIBAgIIQxmrI9A0R1EwCgYIKoZIzj0EAwMwcjEVMBMGA1UEChMM
VHJ1c0F1dGggSW5jMScwJQYDVQQLEx5UcnVzQXV0aCBDZXJ0aWZpY2F0ZSBBdXRo
b3JpdHkxMDAuBgNVBAMTJ1RydXNBdXRoIEhpZ2ggQXNzdXJhbmNlIEVWIFJvb3Qg
Q0EgLSBHNDAgFw0yMjAxMDEwMDAwMDBaGA8yMDUxMTIzMTIzNTk1OVowcjEVMBMG
A1UEChMMVHJ1c0F1dGggSW5jMScwJQYDVQQLEx5UcnVzQXV0aCBDZXJ0aWZpY2F0
ZSBBdXRob3JpdHkxMDAuBgNVBAMTJ1RydXNBdXRoIEhpZ2ggQXNzdXJhbmNlIEVW
IFJvb3QgQ0EgLSBHNDB2MBAGByqGSM49AgEGBSuBBAAiA2IABGHWbwYrT098LpuI
nNcKgneyRjKmLwHEXNbG7PB+NcTetQZSAclIG5g2Z2nCbvFd9y9f9svExT8UgiXB
Fug6C7BfF57CgvvAFNqYlAROWNeLwZxGXWHPHsNvVdlQQ345naOB0zCB0DCBjQYD
VR0jBIGFMIGCoXakdDByMRUwEwYDVQQKEwxUcnVzQXV0aCBJbmMxJzAlBgNVBAsT
HlRydXNBdXRoIENlcnRpZmljYXRlIEF1dGhvcml0eTEwMC4GA1UEAxMnVHJ1c0F1
dGggSGlnaCBBc3N1cmFuY2UgRVYgUm9vdCBDQSAtIEc0gghDGasj0DRHUTAPBgNV
HRMBAf8EBTADAQH/MB0GA1UdDgQWBBTFbnZgIQw9LloAm9yNfln8oDfYdzAOBgNV
HQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwMDZwAwZAIwZjmCGvOWzytff4OEAvT390Sv
wtb+otoQBRPd8wT6xaf2XHqkGnLs7YULamp9HyrmAjBEVtfOFmVSW8eBT/U3vsdP
5eiOQ4/aDDsAOnBwtEuTMkxI9dZMsaugx7Y95nBnEF8=
-----END CERTIFICATE-----

### CT Policy

- [X] We are subscribed to the [Certificate Transparency Policy Google Group](https://groups.google.com/a/chromium.org/g/ct-policy)

**Comment by pgporada** [comment]
Hi @LeviMarvin,

Thank you for submitting all of these root inclusion requests. At this time I will not be accepting these roots into Sapling. Instead, my suggestion is to use the [ct-test-srv](https://github.com/letsencrypt/ct-log-metadata#ct-test-srv) software to test your CA implementation in preparation for your roots being accepted into the Mozilla/Chrome/Apple CA root programs. Once progress has been made getting your root certificates incorporated into those WebPKI root programs, I'd be happy to add your roots to Sapling.

> Sapling is a preproduction log, intended for certificates which are not publicly trusted, but *which are issued by Certificate Authorities who either issue or are expected to issue publicly trusted certificates*.
